### ISSUE TITLE
机器人不理我啊，注册不了

### ISSUE THREAD

**Issue by li505042383** [zybwh/qq_chat_jx3_bot#3]

**Comment by zybwh** [comment]
你用的是最新的commit吗？新的话有一个全局开启和关闭功能，要开启后才能注册

开启需要SUPERUSER权限，需要你在https://github.com/zybwh/qq_chat_jx3_bot/blob/master/qq_chat_jx3_nonebot/config.py
这里的SUPERUSERS里加入你管理员的qq，然后重启bot，发送”开启“到机器人qq就行了。

**Comment by li505042383** [comment]
不是啊，用的老的，新的那个安装到一半出错。




------------------ 原始邮件 ------------------
发件人: "zybwh"<notifications@github.com>; 
发送时间: 2019年6月10日(星期一) 下午5:57
收件人: "zybwh/qq_chat_jx3_bot"<qq_chat_jx3_bot@noreply.github.com>; 
抄送: "..."<505042383@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [zybwh/qq_chat_jx3_bot] 机器人不理我啊，注册不了 (#3)




你用的是最新的commit吗？新的话有一个全局开启和关闭功能，要开启后才能注册
 
开启需要SUPERUSER权限，需要你在https://github.com/zybwh/qq_chat_jx3_bot/blob/master/qq_chat_jx3_nonebot/config.py
 这里的SUPERUSERS里加入你管理员的qq，然后重启bot，发送”开启“到机器人qq就行了。

**Comment by zybwh** [comment]
老的话你看看CQHandler.log里有啥

**Comment by li505042383** [comment]
> 老的话你看看CQHandler.log里有啥

2019-06-10 18:02:19 CQHandler.py[line:26] ERROR No module named _sqlite3
Traceback (most recent call last):
  File "D:\酷Q Air\app\com.github.zybwh.qq_chat_jx3_bot\CQHandler.py", line 24, in <module>
    import Jx3Handler
  File "D:\酷Q Air\app\com.github.zybwh.qq_chat_jx3_bot\Jx3Handler.py", line 20, in <module>
    import sqlite3
  File ".\Lib\sqlite3\__init__.py", line 24, in <module>
  File ".\Lib\sqlite3\dbapi2.py", line 28, in <module>
ImportError: No module named _sqlite3
2019-06-10 18:02:19 CQHandler.py[line:39] INFO __init__
2019-06-10 18:02:19 CQHandler.py[line:55] INFO []
2019-06-10 18:02:19 CQHandler.py[line:78] INFO OnEvent_Enable
2019-06-10 18:03:57 D:\酷Q Air\app\com.github.zybwh.qq_chat_jx3_bot\CQHandler.py[line:92] INFO OnEvent_GroupMsg: subType=1, sendTime=58, fromGroup=33730758, fromQQ=505042383, fromAnonymous=, msg=注册, font=89783016
2019-06-10 18:03:57 CQHandler.py[line:65] INFO _register_group: 33730758
2019-06-10 18:03:57 CQHandler.py[line:75] ERROR global name 'Jx3Handler' is not defined
Traceback (most recent call last):
  File "D:\酷Q Air\app\com.github.zybwh.qq_chat_jx3_bot\CQHandler.py", line 70, in _register_group
    self.group_data[str(fromGroup)] = Jx3Handler.Jx3Handler(int(fromGroup))
NameError: global name 'Jx3Handler' is not defined

**Comment by li505042383** [comment]
[CQHandler.log](https://github.com/zybwh/qq_chat_jx3_bot/files/3271574/CQHandler.log)

**Comment by zybwh** [comment]
File "D:\酷Q Air\app\com.github.zybwh.qq_chat_jx3_bot\Jx3Handler.py", line 20, in 
import sqlite3
出错是这个，sqlite3不在，不过我也没用到，你试试删掉这行？

**Comment by li505042383** [comment]
好像可以了，谢谢大佬！！！

**Comment by zybwh** [comment]
其实我更建议用新的，因为旧的有些bug而且好久没更新了，新的安装的时候有什么问题呀？

或者你要是觉得安装麻烦直接把我host的机器人拉到你群里好了

**Comment by li505042383** [comment]
就是那个NoneBot安装问题

**Comment by zybwh** [comment]
是安装的时候出错还是用的时候出错？

**Comment by li505042383** [comment]
安装
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> pip install nonebot
  File "<stdin>", line 1
    pip install nonebot
              ^
SyntaxError: invalid syntax
>>> pip3 install nonebot
  File "<stdin>", line 1
    pip3 install nonebot
               ^
SyntaxError: invalid syntax
>>>

**Comment by li505042383** [comment]
> 是安装的时候出错还是用的时候出错？

PS D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot> python bot.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2019-06-10 19:47:28,268 nonebot] INFO: Succeeded to import "jx3.plugins.messager"
[2019-06-10 19:47:28,273 nonebot] ERROR: Failed to import "jx3.plugins.tieba", error: No module named 'bs4'
[2019-06-10 19:47:28,274 nonebot] ERROR: No module named 'bs4'
Traceback (most recent call last):
  File "C:\Users\li505\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\plugin.py", line 31, in load_plugin
    module = importlib.import_module(module_name)
  File "C:\Users\li505\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot\jx3\plugins\tieba\__init__.py", line 3, in <module>
    import jx3.plugins.tieba.TiebaHandler
  File "D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot\jx3\plugins\tieba\TiebaHandler.py", line 10, in <module>
    from bs4 import BeautifulSoup
ModuleNotFoundError: No module named 'bs4'
[2019-06-10 19:47:28,278 nonebot] INFO: Running on 0.0.0.0:8080
Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2019-06-10 19:47:28,282] ASGI Framework Lifespan error, continuing without Lifespan support
load group complete

**Comment by zybwh** [comment]
啊，你需要装bs4，我忘记写了

pip install bs4

**Comment by li505042383** [comment]
。。。

**Comment by zybwh** [comment]
嘛文档更新赶不上代码更新

**Comment by li505042383** [comment]
> 嘛文档更新赶不上代码更新

Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Windows\system32> pip install bs4
Collecting bs4
  Downloading https://files.pythonhosted.org/packages/10/ed/7e8b97591f6f456174139ec089c769f89a94a1a4025fe967691de971f314/bs4-0.0.1.tar.gz
Collecting beautifulsoup4 (from bs4)
  Downloading https://files.pythonhosted.org/packages/1d/5d/3260694a59df0ec52f8b4883f5d23b130bc237602a1411fa670eae12351e/beautifulsoup4-4.7.1-py3-none-any.whl (94kB)
    100% |████████████████████████████████| 102kB 31kB/s
Collecting soupsieve>=1.2 (from beautifulsoup4->bs4)
  Downloading https://files.pythonhosted.org/packages/b9/a5/7ea40d0f8676bde6e464a6435a48bc5db09b1a8f4f06d41dd997b8f3c616/soupsieve-1.9.1-py2.py3-none-any.whl
Installing collected packages: soupsieve, beautifulsoup4, bs4
  Running setup.py install for bs4 ... done
Successfully installed beautifulsoup4-4.7.1 bs4-0.0.1 soupsieve-1.9.1
You are using pip version 19.0.3, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Windows\system32> d:
PS D:\> cd D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot
PS D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot> python bot.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2019-06-10 20:13:03,731 nonebot] INFO: Succeeded to import "jx3.plugins.messager"
[2019-06-10 20:13:03,804 nonebot] ERROR: Failed to import "jx3.plugins.tieba", error: 'NoneType' object has no attribute 'scheduled_job'
[2019-06-10 20:13:03,804 nonebot] ERROR: 'NoneType' object has no attribute 'scheduled_job'
Traceback (most recent call last):
  File "C:\Users\li505\AppData\Local\Programs\Python\Python37\lib\site-packages\nonebot\plugin.py", line 31, in load_plugin
    module = importlib.import_module(module_name)
  File "C:\Users\li505\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot\jx3\plugins\tieba\__init__.py", line 3, in <module>
    import jx3.plugins.tieba.TiebaHandler
  File "D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot\jx3\plugins\tieba\TiebaHandler.py", line 154, in <module>
    @nonebot.scheduler.scheduled_job('cron', hour='*')
AttributeError: 'NoneType' object has no attribute 'scheduled_job'
[2019-06-10 20:13:03,807 nonebot] INFO: Running on 0.0.0.0:8080
Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2019-06-10 20:13:03,808] ASGI Framework Lifespan error, continuing without Lifespan support
load group complete
 接下来怎么办

**Comment by zybwh** [comment]
你没有安装nonebot apscheduler
pip install "nonebot[scheduler]"

**Comment by li505042383** [comment]
PS C:\Windows\system32> d:
PS D:\> cd D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot
PS D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot> python bot.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2019-06-10 21:04:47,736 nonebot] INFO: Succeeded to import "jx3.plugins.messager"
[2019-06-10 21:04:47,839 nonebot] INFO: Succeeded to import "jx3.plugins.tieba"
[2019-06-10 21:04:47,839 nonebot] INFO: Running on 0.0.0.0:8080
Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2019-06-10 21:04:47,840] ASGI Framework Lifespan error, continuing without Lifespan support
[2019-06-10 21:04:47,843 nonebot] INFO: Scheduler started
load group complete
可以了？怎么接入机器人？

**Comment by zybwh** [comment]
你cq那边设置好了吗https://cqhttp.cc/docs/4.10/#/?id=%E6%89%8B%E5%8A%A8%E5%AE%89%E8%A3%85

**Comment by li505042383** [comment]
就下载Releases扔进app里吗？

**Comment by li505042383** [comment]
Windows PowerShell
版权所有 (C) Microsoft Corporation。保留所有权利。

PS C:\Windows\system32> d:
PS D:\> cd D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot
PS D:\cqair\qq_chat_jx3_bot\qq_chat_jx3_nonebot> python bot.py
ujson module not found, using json
msgpack not installed, MsgPackSerializer unavailable
[2019-06-10 22:08:58,552 nonebot] INFO: Succeeded to import "jx3.plugins.messager"
[2019-06-10 22:08:58,675 nonebot] INFO: Succeeded to import "jx3.plugins.tieba"
[2019-06-10 22:08:58,675 nonebot] INFO: Running on 0.0.0.0:8080
Running on https://0.0.0.0:8080 (CTRL + C to quit)
[2019-06-10 22:08:58,676] ASGI Framework Lifespan error, continuing without Lifespan support
[2019-06-10 22:08:58,678 nonebot] INFO: Scheduler started
load group complete

**Comment by zybwh** [comment]
还要设置config，https://none.rclab.tk/guide/getting-started.html#%E9%85%8D%E7%BD%AE-coolq-http-api-%E6%8F%92%E4%BB%B6

**Comment by li505042383** [comment]
好像成功了，但是新版只能用818的那几个指令，其他都没反应，要两个一起开吗？

**Comment by zybwh** [comment]
新的话有一个全局开启和关闭功能，要开启后才能注册

开启需要SUPERUSER权限，需要你在https://github.com/zybwh/qq_chat_jx3_bot/blob/master/qq_chat_jx3_nonebot/config.py
这里的SUPERUSERS里加入你管理员的qq，然后重启bot，发送”开启“到机器人qq就行了。

**Comment by li505042383** [comment]
哦，对，忘了这个

**Comment by li505042383** [comment]
好像不行，发送了开启没反应

**Comment by li505042383** [comment]
[2019-06-11 18:46:51,751 nonebot] INFO: Self: 290759076, Message 310 from 505042383@[群:33730758]: 开启
[2019-06-11 18:46:51,751 nonebot] DEBUG: Parsing command: 开启
[2019-06-11 18:46:51,752 nonebot] DEBUG: Matched command start: (empty)
[2019-06-11 18:46:51,753 nonebot] DEBUG: Split command name: ('开启',)
[2019-06-11 18:46:51,753 nonebot] DEBUG: Command ('开启',) found, function: <function start_bot at 0x000002B910F48AE8>
[2019-06-11 18:46:51,754 nonebot] DEBUG: Not to me, ignored
[2019-06-11 18:47:29,045 nonebot] INFO: Self: 290759076, Message 311 from 505042383: 开启
[2019-06-11 18:47:29,046 nonebot] DEBUG: Parsing command: 开启
[2019-06-11 18:47:29,047 nonebot] DEBUG: Matched command start: (empty)
[2019-06-11 18:47:29,047 nonebot] DEBUG: Split command name: ('开启',)
[2019-06-11 18:47:29,048 nonebot] DEBUG: Command ('开启',) found, function: <function start_bot at 0x000002B910F48AE8>
[2019-06-11 18:47:29,049 nonebot] DEBUG: New session of command ('开启',) created
[2019-06-11 18:47:29,049 nonebot] DEBUG: Running command ('开启',)
[2019-06-11 18:47:29,050 nonebot] DEBUG: Session of command ('开启',) finished

**Comment by zybwh** [comment]
开启要@机器人

**Comment by li505042383** [comment]
[2019-06-11 18:49:18,752 nonebot] INFO: Self: 290759076, Message 317 from 505042383@[群:33730758]: [CQ:at,qq=290759076] 开启
[2019-06-11 18:49:18,753 nonebot] DEBUG: Parsing command: 开启
[2019-06-11 18:49:18,754 nonebot] DEBUG: Matched command start: (empty)
[2019-06-11 18:49:18,754 nonebot] DEBUG: Split command name: ('开启',)
[2019-06-11 18:49:18,755 nonebot] DEBUG: Command ('开启',) found, function: <function start_bot at 0x000002B910F48AE8>
[2019-06-11 18:49:18,755 nonebot] DEBUG: New session of command ('开启',) created
[2019-06-11 18:49:18,756 nonebot] DEBUG: Running command ('开启',)
[2019-06-11 18:49:18,756 nonebot] DEBUG: Session of command ('开启',) finished

**Comment by zybwh** [comment]
看一下data/bot.log

**Comment by li505042383** [comment]
[bot.log](https://github.com/zybwh/qq_chat_jx3_bot/files/3276082/bot.log)

**Comment by zybwh** [comment]
hmm你superuser加完后重启nonebot了吗

**Comment by li505042383** [comment]
只重启了机器人

**Comment by zybwh** [comment]
要重启nonebot，现在机器人是不用重启了因为机器人那边只是转发指令到nonebot，所有的逻辑都是在nonebot这边

**Comment by li505042383** [comment]
可以了，非常感谢！！

**Comment by zybwh** [comment]
感觉bug还挺多的，你要是发现了请通知我，谢啦

**Comment by li505042383** [comment]
ok！
